bioimageio_core_version: 0.5.3.post2
bioimageio_spec_version: 0.4.5.post11
rdf_sha256: e00744886e03b8c48ae1c6816e3be730ec910402acd10a5f425e20692bd77785
status: passed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.5post11
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.5 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {tags: 'Missing tags for categories: [{''framework'': [''tensorflow'',
        ''pytorch'', ''tensorflow.js'']}, {''task'': [''semantic-segmentation'', ''instance-segmentation'',
        ''object-detection'', ''image-classification'', ''denoising'', ''image-restoration'',
        ''image-reconstruction'', ''in-silico-labeling'']}]'}
  - bioimageio_spec_version: 0.4.5post11
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.5
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {tags: 'Missing tags for categories: [{''framework'': [''tensorflow'',
        ''pytorch'', ''tensorflow.js'']}, {''task'': [''semantic-segmentation'', ''instance-segmentation'',
        ''object-detection'', ''image-classification'', ''denoising'', ''image-restoration'',
        ''image-reconstruction'', ''in-silico-labeling'']}]'}
  - {bioimageio_core_version: 0.5.3post2, bioimageio_spec_version: 0.4.5post11, error: null,
    name: reproduced test outputs from test inputs, status: passed, traceback: null}
  deepimagej:
  - bioimageio_core_version: 0.5.3post2
    bioimageio_spec_version: 0.4.5post7
    error: 'unsupported operand type(s) for +: ''PosixPath'' and ''str'''
    name: reproduce test outputs with deepimagej 2.1.13 using keras_hdf5 weights
    reason: error
    status: failed
    traceback: ["  File \"/home/runner/work/models/models/scripts/check_rdf_and_test_model.py\",
        line 122, in test_resource\n    error = (error or \"\") + download_deepimagej_model(fiji_path,
        rdf_path)\n", "  File \"/home/runner/work/models/models/scripts/utils.py\",
        line 27, in download_deepimagej_model\n    os.makedirs(fiji_dir + \"//models\")\n"]
  - bioimageio_core_version: 0.5.3post2
    bioimageio_spec_version: 0.4.5post7
    error: 'unsupported operand type(s) for +: ''PosixPath'' and ''str'''
    name: reproduce test outputs with deepimagej 2.1.13 using tensorflow_saved_model_bundle
      weights
    reason: error
    status: failed
    traceback: ["  File \"/home/runner/work/models/models/scripts/check_rdf_and_test_model.py\",
        line 122, in test_resource\n    error = (error or \"\") + download_deepimagej_model(fiji_path,
        rdf_path)\n", "  File \"/home/runner/work/models/models/scripts/utils.py\",
        line 27, in download_deepimagej_model\n    os.makedirs(fiji_dir + \"//models\")\n"]
  ilastik:
  - {bioimageio_core_version: 0.5.1, bioimageio_spec_version: 0.4.5post3, error: null,
    name: reproduce test outputs with ilastik 1.4.0b26 using tensorflow_saved_model_bundle
      weights, reason: null, status: passed, traceback: null}
  - {error: Missing/invalid weight formats for 10.5281/zenodo.5817052/5906839, name: reproduce
      test outputs with ilastik 1.4.0b26, reason: error, status: failed}
  - bioimageio_core_version: 0.5.1
    bioimageio_spec_version: 0.4.5post3
    error: '''str'' object has no attribute ''decode'''
    name: reproduce test outputs with ilastik 1.4.0b26 using keras_hdf5 weights
    reason: error
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 148, in test_resource\n    bioimageio_model=model, devices=devices, weight_format=weight_format\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 103, in __enter__\n    self.load()\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 143, in load\n    self._model.load()\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 41, in load\n    self._load(devices=devices or self.default_devices)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_keras_model_adapter.py\",
        line 39, in _load\n    self._model = keras.models.load_model(weight_file)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py\",
        line 146, in load_model\n    return hdf5_format.load_model_from_hdf5(filepath,
        custom_objects, compile)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py\",
        line 210, in load_model_from_hdf5\n    model_config = json.loads(model_config.decode('utf-8'))\n"]
  - {error: Missing/invalid weight formats for 10.5281/zenodo.5817052/5906839, name: reproduce
      test outputs with ilastik 1.4.0b27, reason: error, status: failed}
  - bioimageio_core_version: 0.5.3post2
    bioimageio_spec_version: 0.4.5post6
    error: 'Failed to download https://zenodo.org/api/files/5a9cfb56-3a5d-4796-986d-8f46b7987b92/per_sample_scale_range.ijm
      (502 Server Error: Bad Gateway for url: https://zenodo.org/api/files/5a9cfb56-3a5d-4796-986d-8f46b7987b92/per_sample_scale_range.ijm)'
    name: reproduce test outputs with ilastik 1.4.0b27 using keras_hdf5 weights
    reason: error
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 39, in test_model\n    model_rdf, weights_priority_order=None if weight_format
        is None else [weight_format]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/io_.py\",
        line 57, in load_resource_description\n    rd: ResourceDescription = resolve_raw_resource_description(raw_rd=raw_rd,
        nodes_module=nodes)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/utils.py\",
        line 112, in resolve_raw_resource_description\n    rd = UriNodeTransformer(root_path=raw_rd.root_path,
        uri_only_if_in_package=uri_only_if_in_package).transform(raw_rd)\n", "  File
        \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 86, in generic_transformer\n    node, **{n: self.transform(value, name=n,
        parent=node) for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 86, in <dictcomp>\n    node, **{n: self.transform(value, name=n, parent=node)
        for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 86, in generic_transformer\n    node, **{n: self.transform(value, name=n,
        parent=node) for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 86, in <dictcomp>\n    node, **{n: self.transform(value, name=n, parent=node)
        for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 60, in transform_list\n    return [self.transform(subnode, **kwargs)
        for subnode in node]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 60, in <listcomp>\n    return [self.transform(subnode, **kwargs) for
        subnode in node]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 206, in transform_URI\n    local_path = _resolve_source(node, root_path=self.root_path)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/functools.py\",
        line 840, in wrapper\n    return dispatch(args[0].__class__)(*args, **kw)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/_resolve_source.py\",
        line 212, in _resolve_source_uri_node\n    local_path = _download_url(path_or_remote_uri,
        output)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/_resolve_source.py\",
        line 396, in _download_url\n    raise RuntimeError(f\"Failed to download {uri}
        ({e})\")\n"]
  - bioimageio_core_version: 0.5.3post2
    bioimageio_spec_version: 0.4.5post6
    error: 'Failed to download https://zenodo.org/api/files/5a9cfb56-3a5d-4796-986d-8f46b7987b92/per_sample_scale_range.ijm
      (502 Server Error: Bad Gateway for url: https://zenodo.org/api/files/5a9cfb56-3a5d-4796-986d-8f46b7987b92/per_sample_scale_range.ijm)'
    name: reproduce test outputs with ilastik 1.4.0b27 using tensorflow_saved_model_bundle
      weights
    reason: error
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 39, in test_model\n    model_rdf, weights_priority_order=None if weight_format
        is None else [weight_format]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/io_.py\",
        line 57, in load_resource_description\n    rd: ResourceDescription = resolve_raw_resource_description(raw_rd=raw_rd,
        nodes_module=nodes)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/utils.py\",
        line 112, in resolve_raw_resource_description\n    rd = UriNodeTransformer(root_path=raw_rd.root_path,
        uri_only_if_in_package=uri_only_if_in_package).transform(raw_rd)\n", "  File
        \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 86, in generic_transformer\n    node, **{n: self.transform(value, name=n,
        parent=node) for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 86, in <dictcomp>\n    node, **{n: self.transform(value, name=n, parent=node)
        for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 86, in generic_transformer\n    node, **{n: self.transform(value, name=n,
        parent=node) for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 86, in <dictcomp>\n    node, **{n: self.transform(value, name=n, parent=node)
        for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 60, in transform_list\n    return [self.transform(subnode, **kwargs)
        for subnode in node]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 60, in <listcomp>\n    return [self.transform(subnode, **kwargs) for
        subnode in node]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 206, in transform_URI\n    local_path = _resolve_source(node, root_path=self.root_path)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/functools.py\",
        line 840, in wrapper\n    return dispatch(args[0].__class__)(*args, **kw)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/_resolve_source.py\",
        line 212, in _resolve_source_uri_node\n    local_path = _download_url(path_or_remote_uri,
        output)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/_resolve_source.py\",
        line 396, in _download_url\n    raise RuntimeError(f\"Failed to download {uri}
        ({e})\")\n"]
