bioimageio_core_version: 0.5.3.post2
bioimageio_spec_version: 0.4.5.post4
rdf_sha256: 4949e3fe5ac2f4b43f2d5b7c388cff008a418be07415295729f32a9d2dd5ef10
status: passed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.5post4
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.5 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_spec_version: 0.4.5post4
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.5
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {}
  - {bioimageio_core_version: 0.5.3post2, bioimageio_spec_version: 0.4.5post4, error: null,
    name: reproduced test outputs from test inputs, status: passed, traceback: null}
  ilastik:
  - bioimageio_core_version: 0.5.3post2
    bioimageio_spec_version: 0.4.5post6
    error: No module named 'tensorflow'
    name: reproduce test outputs with ilastik <todo version> (draft) using tensorflow_saved_model_bundle
      weights
    reason: error
    status: failed
    traceback: ["  File \"/home/runner/.local/lib/python3.8/site-packages/bioimageio/core/resource_tests.py\",
        line 147, in test_resource\n    with create_prediction_pipeline(\n", "  File
        \"/home/runner/.local/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 195, in create_prediction_pipeline\n    model_adapter: ModelAdapter =
        create_model_adapter(\n", "  File \"/home/runner/.local/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 113, in create_model_adapter\n    adapter_cls = _get_model_adapter(weight)\n",
      "  File \"/home/runner/.local/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 133, in _get_model_adapter\n    from ._tensorflow_model_adapter import
        TensorflowModelAdapter\n", "  File \"/home/runner/.local/lib/python3.8/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_tensorflow_model_adapter.py\",
        line 6, in <module>\n    import tensorflow as tf\n"]
