bioimageio_core_version: 0.5.7
bioimageio_spec_version: 0.4.8.post1
rdf_sha256: 8cb24ed7098ff940050627223cdfcc1ebdef0e2c71d81673f420c6a22a886915
status: failed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.8post1
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.8 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {license: GPL-3.0 (GNU General Public License v3.0 only) is deprecated.,
      tags: 'Missing tags for categories: [{''modality'': [''electron-microscopy'',
        ''cryo-electron-microscopy'', ''fluorescence-light-microscopy'', ''transmission-light-microscopy'',
        ''super-resolution-microscopy'', ''x-ray-microscopy'', ''force-microscopy'',
        ''high-content-imaging'', ''whole-slide-imaging'', ''other'']}, {''dims'':
        [''2d'', ''3d'', ''2d-t'', ''3d-t'']}, {''content'': [''cells'', ''nuclei'',
        ''extracellular-vesicles'', ''tissue'', ''plant'', ''mitochondria'', ''vasculature'',
        ''cell-membrane'', ''brain'', ''whole-organism'']}, {''framework'': [''tensorflow'',
        ''pytorch'', ''tensorflow.js'']}, {''software'': [''ilastik'', ''imagej'',
        ''fiji'', ''imjoy'', ''deepimagej'', ''n2v'']}, {''network'': [''unet'', ''densenet'',
        ''resnet'', ''inception'', ''shufflenet'']}, {''task'': [''semantic-segmentation'',
        ''instance-segmentation'', ''object-detection'', ''image-classification'',
        ''denoising'', ''image-restoration'', ''image-reconstruction'', ''in-silico-labeling'']}]'}
  - bioimageio_spec_version: 0.4.8post1
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.8
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {license: GPL-3.0 (GNU General Public License v3.0 only) is deprecated.,
      tags: 'Missing tags for categories: [{''modality'': [''electron-microscopy'',
        ''cryo-electron-microscopy'', ''fluorescence-light-microscopy'', ''transmission-light-microscopy'',
        ''super-resolution-microscopy'', ''x-ray-microscopy'', ''force-microscopy'',
        ''high-content-imaging'', ''whole-slide-imaging'', ''other'']}, {''dims'':
        [''2d'', ''3d'', ''2d-t'', ''3d-t'']}, {''content'': [''cells'', ''nuclei'',
        ''extracellular-vesicles'', ''tissue'', ''plant'', ''mitochondria'', ''vasculature'',
        ''cell-membrane'', ''brain'', ''whole-organism'']}, {''framework'': [''tensorflow'',
        ''pytorch'', ''tensorflow.js'']}, {''software'': [''ilastik'', ''imagej'',
        ''fiji'', ''imjoy'', ''deepimagej'', ''n2v'']}, {''network'': [''unet'', ''densenet'',
        ''resnet'', ''inception'', ''shufflenet'']}, {''task'': [''semantic-segmentation'',
        ''instance-segmentation'', ''object-detection'', ''image-classification'',
        ''denoising'', ''image-restoration'', ''image-reconstruction'', ''in-silico-labeling'']}]'}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8post1
    error: null
    name: load resource description
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8post1
    error: https://bioimage-io.github.io/collection-bioimage-io/rdfs/10.5281/zenodo.7315440/7315441/rdf.yaml
    name: All URLs and paths available
    nested_errors: null
    status: failed
    traceback: ["  File \"/usr/share/miniconda/envs/7315441/lib/python3.11/site-packages/bioimageio/core/resource_tests.py\",
        line 87, in _test_resource_urls\n    SourceNodeChecker(root_path=rd.root_path).visit(rd)\n",
      "  File \"/usr/share/miniconda/envs/7315441/lib/python3.11/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 34, in visit\n    visitor(node)\n", "  File \"/usr/share/miniconda/envs/7315441/lib/python3.11/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 41, in generic_visit\n    self.visit(value)\n", "  File \"/usr/share/miniconda/envs/7315441/lib/python3.11/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 34, in visit\n    visitor(node)\n", "  File \"/usr/share/miniconda/envs/7315441/lib/python3.11/site-packages/bioimageio/core/resource_io/utils.py\",
        line 38, in visit_URI\n    self._visit_source(node)\n", "  File \"/usr/share/miniconda/envs/7315441/lib/python3.11/site-packages/bioimageio/core/resource_io/utils.py\",
        line 35, in _visit_source\n    raise FileNotFoundError(leaf)\n"]
    warnings: {}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8post1
    error: null
    name: Test documentation completeness.
    status: passed
    traceback: null
    warnings: {documentation: No '# Validation' (sub)section found.}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8post1
    error: null
    name: reproduce test outputs from test inputs
    status: passed
    traceback: null
    warnings:
      non-validation-warnings: ['Device management is not implemented for onnx yet,
          cannot unload model']
  deepimagej:
  - {bioimageio_spec_version: 0.4.8post1, error: rdf does not have a compatible weight
      format, name: Initial compatibility checks with DeepImageJ, status: failed}
  ilastik:
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: null
    name: load resource description
    status: passed
    traceback: null
    warnings: {}
  - {error: null, name: has expected resource type, status: passed, traceback: null}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: null
    name: All URLs and paths available
    nested_errors: null
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: null
    name: Test documentation completeness.
    status: passed
    traceback: null
    warnings: {documentation: No '# Validation' (sub)section found.}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: No module named 'onnxruntime'
    name: reproduce test outputs from test inputs
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 157, in _test_model_inference\n    bioimageio_model=model, devices=devices,
        weight_format=weight_format\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 205, in create_prediction_pipeline\n    bioimageio_model=bioimageio_model,
        devices=devices, weight_format=weight_format\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 132, in create_model_adapter\n    adapter_cls = _get_model_adapter(weight)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 157, in _get_model_adapter\n    from ._onnx_model_adapter import ONNXModelAdapter\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_onnx_model_adapter.py\",
        line 5, in <module>\n    import onnxruntime as rt\n"]
    warnings: {}
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: null
    name: load resource description
    nested_errors: null
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: null
    name: All URLs and paths available
    nested_errors: null
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: null
    name: Test documentation completeness.
    status: passed
    traceback: null
    warnings: {documentation: No '# Validation' (sub)section found.}
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: No module named 'onnxruntime'
    name: reproduce test outputs from test inputs
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 157, in _test_model_inference\n    bioimageio_model=model, devices=devices,
        weight_format=weight_format\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 205, in create_prediction_pipeline\n    bioimageio_model=bioimageio_model,
        devices=devices, weight_format=weight_format\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 132, in create_model_adapter\n    adapter_cls = _get_model_adapter(weight)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 157, in _get_model_adapter\n    from ._onnx_model_adapter import ONNXModelAdapter\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_onnx_model_adapter.py\",
        line 5, in <module>\n    import onnxruntime as rt\n"]
    warnings: {}
