bioimageio_spec_version: 0.4.8.post1
rdf_sha256: 1d9b29891f1d71aa4cc7a61dc4735ab7d8e274c3a391e5974002af7f1cb3c0e6
status: passed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.8post1
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.8 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {tags: 'Missing tags for categories: [{''framework'': [''tensorflow'',
        ''pytorch'', ''tensorflow.js'']}, {''software'': [''ilastik'', ''imagej'',
        ''fiji'', ''imjoy'', ''deepimagej'', ''n2v'']}]'}
  - bioimageio_spec_version: 0.4.8post1
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.8
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {tags: 'Missing tags for categories: [{''framework'': [''tensorflow'',
        ''pytorch'', ''tensorflow.js'']}, {''software'': [''ilastik'', ''imagej'',
        ''fiji'', ''imjoy'', ''deepimagej'', ''n2v'']}]'}
  deepimagej:
  - {bioimageio_spec_version: 0.4.8post1, error: rdf does not have a compatible weight
      format, name: Initial compatibility checks with DeepImageJ, status: failed}
  ilastik:
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: 'Failed to download https://zenodo.org/api/files/dbb607ce-e545-494f-a492-fdc87f974bb4/test_output.npy
      (500 Server Error: INTERNAL SERVER ERROR for url: https://zenodo.org/api/files/dbb607ce-e545-494f-a492-fdc87f974bb4/test_output.npy)'
    name: load resource description
    nested_errors: null
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 202, in _test_load_resource\n    rdf, weights_priority_order=None if
        weight_format is None else [weight_format]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/io_.py\",
        line 57, in load_resource_description\n    rd: ResourceDescription = resolve_raw_node(raw_rd=raw_rd,
        nodes_module=nodes)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/utils.py\",
        line 121, in resolve_raw_node\n    rd = UriNodeTransformer(root_path=raw_rd.root_path,
        uri_only_if_in_package=uri_only_if_in_package).transform(raw_rd)\n", "  File
        \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 56, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 161, in generic_transformer\n    node, **{n: self.transform(value, name=n,
        parent=node) for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 161, in <dictcomp>\n    node, **{n: self.transform(value, name=n, parent=node)
        for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 56, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 62, in transform_list\n    return [self.transform(subnode, **kwargs)
        for subnode in node]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 62, in <listcomp>\n    return [self.transform(subnode, **kwargs) for
        subnode in node]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 56, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 339, in transform_URI\n    local_path = _resolve_source(node, root_path=self.root)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/functools.py\",
        line 840, in wrapper\n    return dispatch(args[0].__class__)(*args, **kw)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/_resolve_source.py\",
        line 253, in _resolve_source_uri_node\n    local_path = _download_url(path_or_remote_uri,
        output, pbar=pbar)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/_resolve_source.py\",
        line 479, in _download_url\n    raise RuntimeError(f\"Failed to download {uri}
        ({e})\") from e\n"]
    warnings: {}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: null
    name: load resource description
    status: passed
    traceback: null
    warnings: {}
  - {error: null, name: has expected resource type, status: passed, traceback: null}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: null
    name: All URLs and paths available
    nested_errors: null
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: null
    name: Test documentation completeness.
    status: passed
    traceback: null
    warnings: {documentation: No '# Validation' (sub)section found.}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: '''str'' object has no attribute ''decode'''
    name: reproduce test outputs from test inputs
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 157, in _test_model_inference\n    bioimageio_model=model, devices=devices,
        weight_format=weight_format\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 122, in __enter__\n    self.load()\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 180, in load\n    self._model.load()\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 57, in load\n    self._load(devices=devices or self.default_devices)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_keras_model_adapter.py\",
        line 41, in _load\n    self._model = keras.models.load_model(weight_file)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py\",
        line 146, in load_model\n    return hdf5_format.load_model_from_hdf5(filepath,
        custom_objects, compile)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py\",
        line 210, in load_model_from_hdf5\n    model_config = json.loads(model_config.decode('utf-8'))\n"]
    warnings:
      non-validation-warnings: ['Model tensorflow version (2, 9) does not match 1.14.0.The
          prediction results may be wrong']
