bioimageio_core_version: 0.5.3.post2
bioimageio_spec_version: 0.4.5.post13
rdf_sha256: f1964f84c61abedaed1edd9605e7ed90c3b2e7c77f2d4a15929780e9469c6946
status: passed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.5post13
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.5 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {license: BSD-2-Clause (BSD 2-Clause "Simplified" License) is not FSF
        Free/libre.}
  - bioimageio_spec_version: 0.4.5post13
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.5
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {license: BSD-2-Clause (BSD 2-Clause "Simplified" License) is not FSF
        Free/libre.}
  - {bioimageio_core_version: 0.5.3post2, bioimageio_spec_version: 0.4.5post13, error: null,
    name: reproduced test outputs from test inputs, status: passed, traceback: null}
  deepimagej: []
  ilastik:
  - bioimageio_core_version: 0.5.1
    bioimageio_spec_version: 0.4.5post3
    error: Unable to open file (file signature not found)
    name: reproduce test outputs with ilastik 1.4.0b26 using keras_hdf5 weights
    reason: error
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 148, in test_resource\n    bioimageio_model=model, devices=devices, weight_format=weight_format\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 103, in __enter__\n    self.load()\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 143, in load\n    self._model.load()\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 41, in load\n    self._load(devices=devices or self.default_devices)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_keras_model_adapter.py\",
        line 39, in _load\n    self._model = keras.models.load_model(weight_file)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py\",
        line 146, in load_model\n    return hdf5_format.load_model_from_hdf5(filepath,
        custom_objects, compile)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py\",
        line 200, in load_model_from_hdf5\n    f = h5py.File(filepath, mode='r')\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/h5py/_hl/files.py\",
        line 507, in __init__\n    fid = make_fid(name, mode, userblock_size, fapl,
        fcpl, swmr=swmr)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/h5py/_hl/files.py\",
        line 220, in make_fid\n    fid = h5f.open(name, flags, fapl=fapl)\n", '  File
        "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

        ', '  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

        ', '  File "h5py/h5f.pyx", line 106, in h5py.h5f.open

        ']
  - bioimageio_core_version: 0.5.3post2
    bioimageio_spec_version: 0.4.5post6
    error: 'Failed to download https://zenodo.org/api/files/da7b84a8-f43a-4a24-93cd-9716be7b2655/unet_pancreatic_cell_segmentation.h5
      (404 Client Error: NOT FOUND for url: https://zenodo.org/api/files/da7b84a8-f43a-4a24-93cd-9716be7b2655/unet_pancreatic_cell_segmentation.h5)'
    name: reproduce test outputs with ilastik 1.4.0b27 using keras_hdf5 weights
    reason: error
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 39, in test_model\n    model_rdf, weights_priority_order=None if weight_format
        is None else [weight_format]\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/io_.py\",
        line 57, in load_resource_description\n    rd: ResourceDescription = resolve_raw_resource_description(raw_rd=raw_rd,
        nodes_module=nodes)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_io/utils.py\",
        line 112, in resolve_raw_resource_description\n    rd = UriNodeTransformer(root_path=raw_rd.root_path,
        uri_only_if_in_package=uri_only_if_in_package).transform(raw_rd)\n", "  File
        \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 86, in generic_transformer\n    node, **{n: self.transform(value, name=n,
        parent=node) for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 86, in <dictcomp>\n    node, **{n: self.transform(value, name=n, parent=node)
        for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 63, in transform_dict\n    return {key: self.transform(value, **kwargs)
        for key, value in node.items()}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 63, in <dictcomp>\n    return {key: self.transform(value, **kwargs) for
        key, value in node.items()}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 86, in generic_transformer\n    node, **{n: self.transform(value, name=n,
        parent=node) for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 86, in <dictcomp>\n    node, **{n: self.transform(value, name=n, parent=node)
        for n, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 206, in transform_URI\n    local_path = _resolve_source(node, root_path=self.root_path)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/functools.py\",
        line 840, in wrapper\n    return dispatch(args[0].__class__)(*args, **kw)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/_resolve_source.py\",
        line 212, in _resolve_source_uri_node\n    local_path = _download_url(path_or_remote_uri,
        output)\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/spec/shared/_resolve_source.py\",
        line 396, in _download_url\n    raise RuntimeError(f\"Failed to download {uri}
        ({e})\")\n"]
  - {bioimageio_core_version: 0.5.3post2, bioimageio_spec_version: 0.4.5post6, error: null,
    name: reproduce test outputs with ilastik 1.4.0b27 using tensorflow_saved_model_bundle
      weights, reason: null, status: passed, traceback: null}
  - {bioimageio_core_version: 0.5.1, bioimageio_spec_version: 0.4.5post3, error: null,
    name: reproduce test outputs with ilastik 1.4.0b26 using tensorflow_saved_model_bundle
      weights, reason: null, status: passed, traceback: null}
